name: deploy to Azure Web App

on:
    workflow_run:
      workflows: [dotnet build and deploy to Azure Web App]
      types: [completed]
      branches: [main]
env:
  GH_TOKEN: ${{ secrets.GH_PAT }}
  AZURE_WEBAPP_NAME: mywebapi1234 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - name: Get the latest Run ID for ci.yml build workflow
        run: |
          a=$(gh run --repo michaeldacey/dotnetdemo list --workflow ci.yml --json databaseId --jq .[0].databaseId)&&echo "RUN_ID=$a" >> $GITHUB_ENV
          echo $a
      - name: Download the artifact from the build workflow
        uses: actions/download-artifact@v4
        with:
          name: myappartifact
          # token with actions:read permissions on target repo
          github-token: ${{ secrets.GH_PAT }} 
          repository: michaeldacey/dotnetdemo
          run-id: ${{env.RUN_ID}}

      # Login to Azure using Workflow Identity Federation
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Deploy to Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: api/publish
          