on:
    workflow_run:
      workflows: [dotnet build and deploy to Azure Web App]
      types: [completed]
      branches: [main]
env:
  GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - name: Get the latest Run ID for ci.yml build workflow
        run: |
          a=$(gh run --repo michaeldacey/dotnetdemo list --workflow ci.yml --json databaseId --jq .[0].databaseId)&&echo "RUN_ID=$a" >> $GITHUB_ENV
          echo $a
      - name: Download the artifact from the build workflow
        uses: actions/download-artifact@v4
        with:
          name: myappartifact
          # token with actions:read permissions on target repo
          github-token: ${{ secrets.GH_PAT }} 
          repository: michaeldacey/dotnetdemo
          run-id: ${{env.RUN_ID}}
  